# Generated by Django 4.2 on 2026-02-02 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_start_time', models.TimeField(default=datetime.time(8, 0), help_text='Class start time (8:00 AM by default)')),
                ('late_threshold_minutes', models.IntegerField(default=30, help_text='Minutes after start time to mark as late (default: 30 min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Class Settings',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='login_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', max_length=20),
        ),
    ]
